version: '3'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/app
        depends_on:
            - mongodb_container
        environment:
            SECRET_KEY: 'hange this'
            DEFAULT_PASSWORD: 'hangethis'
            DEFAULT_USERNAME: 'hange@this.ro'
            COVID_BACKEND_USER: 'tg-bot@test.com'
            TG_IP: '192.168.100.23'
   
    mongodb_container:
        image: mongo:latest
        volumes:
            - mongodb_data_container1:/data/db

volumes:
    mongodb_data_container1: