version: '3'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/app
        depends_on:
            - mongodb_container
        environment:
            SECRET_KEY: ${SECRET_KEY}
            DEFAULT_PASSWORD: ${DEFAULT_PASSWORD}
            DEFAULT_USERNAME: ${DEFAULT_USERNAME}

    mongodb_container:
        image: mongo:latest
        volumes:
            - mongodb_data_container1:/data/db

volumes:
    mongodb_data_container1: