version: '3'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/app
        depends_on:
            - mongodb_container
            - tgbot
    tgbot:
        build: tgbot/
        ports:
            - "5001:5001"
        environment:
            TELEGRAM_TOKEN: changethis
            COVID_BACKEND: http://web:5000/api
            COVID_BACKEND_USER: changethis
            COVID_BACKEND_PASS: changethis
        volumes:
            - ./tgbot:/app

    mongodb_container:
        image: mongo:latest
        # environment:
        #     MONGO_INITDB_ROOT_USERNAME: root
        #     MONGO_INITDB_ROOT_PASSWORD: rootpassword
        ports:
            - 27017:27017
        volumes:
            - mongodb_data_container1:/data/db

volumes:
    mongodb_data_container1: